services:
    database:
        image: mysql:latest
        ports:
            - 3306:3306
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: mydb
            
    test-work:
        depends_on:
            database:
                condition: service_healthy
        ports:
            - 8080:8080
        build:
            context: ./
            dockerfile: Dockerfile
        environment:
            DB_URL: jdbc:mysql://database:3306
            DB_NAME: mydb
            DB_USER_NAME: root
            DB_USER_PASSWORD: root
